### ISSUE TITLE
PathFinderCA Releases.

### ISSUE THREAD

**Issue by CantBeKarma** [Fleynaro/PathFinderCA#1]
Not sure if you're even around anymore but you should definitely compile and release the first official version of this lib. It'd especially be useful to have the PathFinderCA plugin pre-compiles available so that the people who can't compile them themselves (like myself atm) have access to them.

**Comment by Fragrus** [comment]
How wonderful it would be if you compiled this plugin ;)

**Comment by Radless0** [comment]
> Not sure if you're even around anymore but you should definitely compile and release the first official version of this lib. It'd especially be useful to have the PathFinderCA plugin pre-compiles available so that the people who can't compile them themselves (like myself atm) have access to them.

**Comment by Crayder** [comment]
[PathFinderCA.zip](https://github.com/Fleynaro/PathFinderCA/files/5140039/PathFinderCA.zip)
Here's a debug build for it, for windows at least. Untested. Straight from VS.
